DROP TABLE CALENDAR
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CAL;

CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000),
	RDATE VARCHAR2(12) NOT NULL,
	WDATE DATE NOT NULL	
);

CREATE SEQUENCE SEQ_CAL
START WITH 1
INCREMENT BY 1;

ALTER TABLE CALENDAR
ADD CONSTRAINT FK_CAL_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

20210601
	:
20210630				


SELECT SEQ, ID, TITLE, CONTENT, RDATE, WDATE
FROM (SELECT ROW_NUMBER()OVER(PARTITION BY SUBSTR(RDATE, 1, 8) ORDER BY RDATE ASC) AS RNUM,
			SEQ, ID, TITLE, CONTENT, RDATE, WDATE 
	  FROM CALENDAR
	  WHERE ID=? AND SUBSTR(RDATE, 1, 6)=? )			-- 202106
WHERE RNUM BETWEEN 1 AND 5;


select * from calendar;

INSERT INTO CALENDAR(SEQ, ID, TITLE, CONTENT, RDATE, WDATE)
VALUES(SEQ_CAL.NEXTVAL, 'aaa', '회먹기약속', '광어', '202106191230', '21/06/18');





